version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=USERNAME
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # lens-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres

volumes:
  postgres:
