# name: Build and Push Docker to EKS

# on:
#   push:
#     branches:
#       - dev

# jobs:                                            
#   build:                                       
#     name: Release                                
#     runs-on: ubuntu-latest         
#     env:
#       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#       DOCKER_REPOSITORY: murky-manager-server-app
#       DOCKER_TAG: dev
#       DEV_AWS_EKS_CLUSTER_NAME: ${{ secrets.DEV_AWS_EKS_CLUSTER_NAME }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Create .env file
#         run: |
#           echo "NODE_ENV=development" >> .env
#           echo "PORT=3001" >> .env
#           echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/mydb?schema=public" >> .env

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           registry: docker.io
#           username: ${{ env.DOCKERHUB_USERNAME }}
#           password: ${{ env.DOCKERHUB_TOKEN }}

#       - name: Set Docker Image
#         run: echo "DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}" >> $GITHUB_ENV

#       - name: Build Docker image
#         run: |
#           docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

#       - name: Push Docker image
#         run: |
#           docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Update kubeconfig context
#         run: |
#           aws eks update-kubeconfig --name ${{ env.DEV_AWS_EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

#       - name: Checkout Helm chart repository
#         uses: actions/checkout@v2
#         with:
#           repository: DarkMurky/murky-view-infrasturcture

#       - name: Install Helm
#         uses: azure/setup-helm@v4.2.0
#         with:
#           version: 'v3.16.4'
#         id: install

#       - name: Deploy with Helm
#         run: |
#           helm upgrade --install my-release ./k8s/murky-view-chart

#       - name: Install Ingress NGINX
#         run: |
#           helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
