name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PORT=3001" >> .env
          echo "DATABASE_URL=postgresql://USERNAME:PASSWORD@postgres:5432/mydb?schema=public" >> .env

      - name: View PostgreSQL logs
        run: docker logs $(docker ps -q --filter "name=postgres")

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t kvait/murky-manager-server-app:dev .

      - name: Push Docker image
        run: |
          docker push kvait/murky-manager-server-app:dev
