name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        name: postgres-service
        image: postgres:latest
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: USERNAME
          POSTGRES_PASSWORD: PASSWORD
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U USERNAME"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PORT=3001" >> .env
          echo "DATABASE_URL=postgresql://USERNAME:PASSWORD@postgres-service:5432/mydb?schema=public" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t kvait/murky-manager-server-app:dev .

      - name: Push Docker image
        run: |
          docker push kvait/murky-manager-server-app:dev
