name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.3
        env:
          POSTGRES_USER: USERNAME
          POSTGRES_PASSWORD: PASSWORD
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U USERNAME"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PORT=3001" >> .env
          echo "DATABASE_URL=postgresql://USERNAME:PASSWORD@postgres:5432/mydb?schema=public" >> .env

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -U USERNAME; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t kvait/murky-manager-server-app:dev .

      # - name: Push Docker image
      #   run: |
      #     docker push kvait/murky-manager-server-app:dev
